version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exercise_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - exercise-network
    restart: always  # Ensures that PostgreSQL restarts if the container crashes

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - exercise-network
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"  # Management console
    networks:
      - exercise-network
    restart: always

networks:
  exercise-network:
    driver: bridge  # Default network driver

volumes:
  postgres_data:
    driver: local  # Persist data locally on the host