openapi: 3.0.0
info:
  title: Exercise API
  description: API for managing exercises
  version: 1.0.0
paths:
  /exercises:
    post:
      summary: Create an exercise
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExerciseRequestDTO'
      responses:
        '201':
          description: Exercise created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExerciseResponseDTO'
components:
  schemas:
    ExerciseRequestDTO:
      type: object
      properties:
        setsReq:
          type: integer
          minimum: 1
          example: 10
          nullable: false
        repsReq:
          type: integer
          minLength: 1
          maxLength: 50
          nullable: false
        bodyPart:
          type: string
          example: "biceps"
          nullable: false
        name:
          type: string
          example: "pull up"
          nullable: false
        description:
          type: string
      required:
        - setsReq
        - repsReq
        - bodyPart
        - name
    ExerciseResponseDTO:
      type: object
      properties:
        id:
          type: integer
        sets:
          type: integer
        reps:
          type: integer
        bodyPart:
          type: string
        name:
          type: string
        description:
          type: string
    ExerciseOpenApiResponseDTO:
      type: object
      properties:
        message:
          type: string

